window.SOP_MODULES=[{
id:'cash',
title:{en:'Cash Handling & Daily Reconciliation',es:'Manejo de Efectivo y Reconciliación Diaria'},
summary:{en:'Safely handle register cash, reconcile each drawer against Shopify POS, document variances, secure funds, and follow approved deposit procedures.',es:'Manejar el efectivo de caja de forma segura, reconciliar cada caja con Shopify POS, documentar diferencias, asegurar los fondos y seguir los procedimientos aprobados de depósito.'},
sections:{en:[
['Purpose & responsibility','This SOP applies to authorized employees handling cash, register reconciliation, deposits, or daily cash reconciliation. Branch Managers enforce the process, review reconciliations, investigate discrepancies, verify deposits, and maintain secure control. Assistant Branch Managers reconcile when assigned and report discrepancies. Sales Associates maintain accurate drawers, report register issues, and notify the Branch Manager when change is needed.'],
['Core cash policy','All cash transactions must be recorded through Shopify POS. Cash may only be removed for approved business purposes by the Branch Manager. Every register is reconciled daily; shortages and overages are documented immediately. Cash stays secured, and only authorized personnel may access the safe or prepare deposits.'],
['Step 1 — Count change','During the last hour of business, verify no transactions remain open and the Branch Manager confirms the register is ready. Count the drawer and leave a $500 BEGINNING BANK for the next day, prioritizing $10s, $5s, $1s, and coins.'],
['Step 2 — Count each drawer','Count each register separately. Record the expected cash total from Shopify POS and the actual physical cash. They should match. Recount for accuracy. Any discrepancy must be reported to the Branch Manager so it can be investigated and documented.'],
['Step 3 — Close the register session','In Shopify POS select REMOVE CASH and enter the physical cash being removed; it should match the expected and actual amount counted. Select CLOSE SESSION, follow NEXT until PRINT RECEIPT appears, print the receipt, wrap it with the cash using a rubber band, and drop the money into the safe.'],
['Step 4 — Reconciliation spreadsheet','For each register, locate today’s date in column A of the Cash Reconciliation spreadsheet. Enter Shopify EXPECTED in column B, actual cash removed in column C, and review the +/- in column D. For multiple registers continue into the next columns. Confirm the file saved before leaving.'],
['Cash variance procedure','If a drawer does not balance: recount it, verify expected and actual totals, confirm the $500 change fund, and verify cash was not placed in another drawer. Notify the Branch Manager immediately. If unresolved, record the variance, document a possible cause if known, initial the reconciliation, and forward to Accounting when required.'],
['Deposits, bank runs & change orders','Deposits are generally prepared Fridays unless directed otherwise. The manager removes deposit cash from the safe, recounts each day’s wrapped cash against its printed receipt, completes the deposit slip, and secures it in a tamper-evident bank bag. For bank runs: bring ID, go directly to the bank, make no personal stops, keep deposits out of sight, obtain a validated receipt, and file it with reconciliation paperwork for Accounting. The Branch Manager maintains change funds and orders required denominations when bills or coins run low.'],
['Cash security standards','Managers ensure the safe stays locked, register drawers stay closed or locked when unattended, keys remain secured, safe combinations remain confidential, and cash is never left unattended.']
],es:[
['Propósito y responsabilidad','Este SOP aplica a empleados autorizados que manejan efectivo, reconciliaciones de caja, depósitos o reconciliación diaria. El Branch Manager hace cumplir el proceso, revisa reconciliaciones, investiga diferencias, verifica depósitos y mantiene control seguro. El Assistant Branch Manager reconcilia cuando se le asigna y reporta diferencias. Los Sales Associates mantienen cajas exactas, reportan problemas y avisan al Branch Manager cuando se necesita cambio.'],
['Política principal de efectivo','Todas las transacciones en efectivo deben registrarse en Shopify POS. El efectivo solo puede retirarse para fines comerciales aprobados por el Branch Manager. Cada caja se reconcilia diariamente; faltantes y sobrantes se documentan inmediatamente. El efectivo permanece seguro y solo personal autorizado puede acceder a la caja fuerte o preparar depósitos.'],
['Paso 1 — Contar el cambio','Durante la última hora del día, confirme que no queden transacciones abiertas y que el Branch Manager autorice el conteo. Cuente la caja y deje un BEGINNING BANK de $500 para el día siguiente, priorizando billetes de $10, $5, $1 y monedas.'],
['Paso 2 — Contar cada caja','Cuente cada registro por separado. Registre el total esperado de Shopify POS y el efectivo físico real. Deben coincidir. Vuelva a contar para confirmar. Cualquier diferencia debe reportarse al Branch Manager para investigación y documentación.'],
['Paso 3 — Cerrar la sesión','En Shopify POS seleccione REMOVE CASH e ingrese el efectivo físico retirado; debe coincidir con el monto esperado y contado. Seleccione CLOSE SESSION, siga NEXT hasta PRINT RECEIPT, imprima el recibo, envuélvalo con el efectivo usando una banda elástica y coloque el dinero en la caja fuerte.'],
['Paso 4 — Hoja de reconciliación','Para cada registro, busque la fecha de hoy en la columna A de la hoja Cash Reconciliation. Ingrese Shopify EXPECTED en la columna B, el efectivo retirado en C y revise el +/- en D. Para múltiples registros continúe en las siguientes columnas. Confirme que el archivo se guardó antes de salir.'],
['Procedimiento de CASH VARIANCE','Si una caja no cuadra: vuelva a contar, verifique totales esperados/reales, confirme el fondo de cambio de $500 y asegúrese de que el efectivo no esté en otra caja. Avise inmediatamente al Branch Manager. Si no se resuelve, registre la diferencia, documente la posible causa si se conoce, ponga sus iniciales y envíe a Accounting cuando corresponda.'],
['Depósitos, viajes al banco y CHANGE ORDERS','Los depósitos normalmente se preparan los viernes salvo otra instrucción. El manager retira el efectivo de la caja fuerte, vuelve a contar el efectivo de cada día contra el recibo impreso, completa la boleta y lo asegura en una bolsa bancaria inviolable. Para ir al banco: lleve identificación, vaya directamente, no haga paradas personales, mantenga el depósito fuera de vista, obtenga recibo validado y archívelo con la reconciliación para Accounting. El Branch Manager mantiene fondos de cambio y solicita denominaciones cuando sean necesarias.'],
['Normas de seguridad','Los managers aseguran que la caja fuerte permanezca cerrada, las cajas registradoras estén cerradas o bloqueadas cuando estén desatendidas, las llaves estén seguras, las combinaciones sean confidenciales y el efectivo nunca quede sin supervisión.']
]},
quiz:{en:[
['How much cash should remain as the BEGINNING BANK?',['$100','$250','$500','$1,000'],2],
['Where must cash transactions be recorded?',['Shopify POS','A paper notebook only','Qoblex only','Email'],0],
['If expected and actual cash do not match, what should happen?',['Ignore a small difference','Notify the Branch Manager so it can be investigated and documented','Change the expected total','Wait until Friday'],1],
['After REMOVE CASH, what is part of the approved close process?',['CLOSE SESSION and print the receipt','Leave the session open','Take the cash home','Discard the receipt'],0],
['Which bank-run practice is required?',['Make personal stops first','Keep the deposit visible','Go directly to the bank and obtain a validated receipt','Leave the receipt at the bank'],2]
],es:[
['¿Cuánto efectivo debe quedar como BEGINNING BANK?',['$100','$250','$500','$1,000'],2],
['¿Dónde deben registrarse las transacciones en efectivo?',['Shopify POS','Solo en un cuaderno','Solo en Qoblex','Correo electrónico'],0],
['Si el efectivo esperado y real no coinciden, ¿qué debe hacerse?',['Ignorar una diferencia pequeña','Avisar al Branch Manager para investigar y documentar','Cambiar el total esperado','Esperar hasta el viernes'],1],
['Después de REMOVE CASH, ¿qué forma parte del cierre aprobado?',['CLOSE SESSION e imprimir el recibo','Dejar la sesión abierta','Llevar el efectivo a casa','Botar el recibo'],0],
['¿Qué práctica es obligatoria al llevar un depósito al banco?',['Hacer paradas personales','Mantener el depósito visible','Ir directamente al banco y obtener un recibo validado','Dejar el recibo en el banco'],2]
]},
practical:{en:['Demonstrate a register count while maintaining the $500 BEGINNING BANK.','Identify Shopify POS expected cash and reconcile it to actual cash.','Demonstrate REMOVE CASH and explain the CLOSE SESSION / PRINT RECEIPT sequence.','Correctly explain how a cash variance is escalated and documented.','Explain how cash, receipts, deposits, keys, and safe access remain secured.'],es:['Demuestre el conteo manteniendo el BEGINNING BANK de $500.','Identifique el efectivo esperado en Shopify POS y reconcílielo con el efectivo real.','Demuestre REMOVE CASH y explique la secuencia CLOSE SESSION / PRINT RECEIPT.','Explique correctamente cómo se escala y documenta un CASH VARIANCE.','Explique cómo se mantienen seguros el efectivo, recibos, depósitos, llaves y acceso a la caja fuerte.']},
source:'Bargain Build, Inc. SOP v1 — Cash Handling & Daily Reconciliaton SOP, Version 1.0'
}];